### ISSUE TITLE
Use a more consistent location for downloading trained model artifacts

### ISSUE THREAD

**Issue by cthoyt** [Kohulan/DECIMER-Image_Transformer#10]
When I ran `decimer` (after #2), it downloaded all of the assets into the current working directory. This isn't desired after the code is packaged, and it would be better to have it download to a consistent location, such as in the home directory. I've spent a lot of time thinking about this and written the [PyStow](https://github.com/cthoyt/pystow) package to support this. I could send a PR after #2 is done that demonstrates what I mean

**Comment by cthoyt** [comment]
@Kohulan was there a fix?

**Comment by Kohulan** [comment]
@cthoyt Yes just fixed it :)
