### ISSUE TITLE
Cannot pass np.array into predict_SMILES() 

### ISSUE THREAD

**Issue by ignaspakamore** [Kohulan/DECIMER-Image_Transformer#109]
### Issue Type

Bug

### Source

GitHub (source)

### DECIMER Image Transformer Version

2

### OS Platform and Distribution

Linux ubuntu

### Python version

3.10

### Current Behaviour?

Following the docstring predict_SMILES() should take str or np.array as argument: 
` image_input (str or np.ndarray): Path of chemical structure depiction image or a numpy array representing the image.`

Nevertheless, only path string can be passed. When passing np.array the error is printed out: 
`'numpy.ndarray' object has no attribute 'read' ...`

### Standalone code to reproduce the issue

```shell
img: np.array

predict_SMILES(img)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kohulan** [comment]
@ignaspakamore Could you provide me the exact DECIMER version installed on your system?

**Comment by ignaspakamore** [comment]
I am using decimer==2.7.0

**Comment by Kohulan** [comment]
Hi @ignaspakamore ,
I have released a new bug fix for decimer==2.7.1. Please check it and let me know if that resolves the issue.

**Comment by ignaspakamore** [comment]
Hi Kohulan, 

I am getting this error now when running python setup.py install: 

`Installed /home/ignas/miniconda3/envs/decimer_test/lib/python3.10/site-packages/numpy-2.1.3-py3.10-linux-x86_64.egg
error: numpy 2.1.3 is installed but numpy<2.0.0,>=1.23.5 is required by {'tensorflow'}
`

**Comment by ignaspakamore** [comment]
Hi @Kohulan, 

Just tested, it works fine. Thank you very much for your help and swift replies!

Ignas
