### ISSUE TITLE
decimer translates images a bit too eagerly

### ISSUE THREAD

**Issue by DocMinus** [Kohulan/DECIMER-Image_Transformer#110]
### Issue Type

Bug

### Source

GitHub (source)

### DECIMER Image Transformer Version

2.7.0

### OS Platform and Distribution

Win 10, GPU: 3060Ti

### Python version

Py 3.11

### Current Behaviour?

I am iterating over a folder of images extracted from a PDF (unfortunately also some trash-images are extracted as one of the below examples). Decimer is a bit too good in trying to convert to smiles.  Even my company logo (not attached) ends up as (valid) molecule. 

### Which images caused the issue? (This is mandatory for images related issues)

![page_2_image_2](https://github.com/user-attachments/assets/761e4779-2d08-46d0-9e58-566d93dfa4bd)
![page_4_image_2](https://github.com/user-attachments/assets/274b6a36-2832-4a1f-9559-0dd3f13265a6)

### Standalone code to reproduce the issue

```shell
Nothing special, basically the test example from the Readme:

from DECIMER import predict_SMILES

# Unleash the power of DECIMER
image_path = "path/to/your/chemical/masterpiece.jpg"
SMILES = predict_SMILES(image_path)
print(f"🎉 Decoded SMILES: {SMILES}")
```

### Relevant log output

```shell
2024-11-01 13:25:57.960520: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From d:\dev\ChemistryDashboard\.conda\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-11-01 13:26:02.978755: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
🎉 Decoded SMILES: C1=CC2=CC=C1C3=CC=C(C=C3)C4=CC=C(C=C4)C5=CC=C(C=C5)C6=CC=C(C=C6)C7=CC=C(C=C7)C8=CC=C2C=C8
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kohulan** [comment]
Hi @DocMinus ,

We are aware of this and integrating a classifier directly into DECIMER could become an overhead. We have already developed a [classifier](https://github.com/Steinbeck-Lab/DECIMER-Image-Classifier/tree/main) . Pass the images through the classifier; those that pass can be used as inputs for DECIMER.

Kind regards,
Kohulan

**Comment by DocMinus** [comment]
Ah, thanks, I missed that, I believe I have seen this at some point but forgot about it :blush:
I will check it out. So far I was able to filter out small trash images by checking for files size and deleting them.

**Comment by fredaddy** [comment]
@DocMinus I was running into the same issue - thanks for flagging. And thanks as always to @Kohulan for building this!

@DocMinus seems like we have some overlapping interests here. Want to chat and see if we can work together?
