### ISSUE TITLE
Add preprint on DECIMER 1.0 to Literature section in README

### ISSUE THREAD

**Issue by steinbeck** [Kohulan/DECIMER-Image_Transformer#14]
Add preprint on DECIMER 1.0 to Literature section in README

**Comment by Kohulan** [comment]
It is already there under Citation:

Rajan, Kohulan; Zielesny, Achim; Steinbeck, Christoph (2021): DECIMER 1.0: Deep Learning for Chemical Image Recognition using Transformers. ChemRxiv. Preprint. https://doi.org/10.26434/chemrxiv.14479287.v1

**Comment by steinbeck** [comment]
I would repeat it under references. If I didn't see it, others also won't.

**Comment by Kohulan** [comment]
Yes I agree, Now modified
