### ISSUE TITLE
Example Question

### ISSUE THREAD

**Issue by whitead** [Kohulan/DECIMER-Image_Transformer#21]
Hi,

This looks like a great resource. I'm trying to get an understanding of how to use this model. I installed from github source and ran the following code:

```py
from decimer import DECIMER
model_name = 'Isomeric'
smiles = DECIMER.predict_SMILES('image.png',model_name)
print(smiles)
```

where the image is 
![Capture](https://user-images.githubusercontent.com/908389/148762368-368826f1-1d43-4c80-913b-4e8ac7fd4530.PNG)

The output was:

`CCCOCCOCCOCCCCCNCCCNCCNCCNCCNCCNCCCCCCCCNNNNNNN`

which is quite far from correct. Do you have any idea what might be going on? Is there some per-processing of the image I need to do? Thank you!

**Comment by Kohulan** [comment]
Hi @whitead ,

Thank you for your interest. currently, our tool only works with images with a scale of 299x299 and the molecule should be centred in the canvas. We are working on an input pipeline and will update the code soon.

-Kohulan

**Comment by whitead** [comment]
I've resized the image to be 299x299 with the molecule centered. Still not getting good results. Any ideas?

![image](https://user-images.githubusercontent.com/908389/148782001-90d0066a-d14c-406a-95ba-35077d8d4a76.png)

**Comment by Adafede** [comment]
Hi,

I was about to post the same...

I took a random image of a structure from Google Images 
![quassin](https://user-images.githubusercontent.com/44283913/149333044-2474dd4d-b190-471f-aed1-9ca1434a5503.jpg)

and ran
```
decimer --model Isomeric --image quassin.jpg
```

which led 
```
COCCNCCOCCNCCOCCNCCCNCCCCCCCCCCCCCNCCNNCNNNCNCN
```
![result](https://user-images.githubusercontent.com/44283913/149333446-bec06372-4504-4beb-bbe8-0ee7a0830eef.jpeg)


Could you comment? Is the image quality sufficient?

**Comment by Kohulan** [comment]
Hi @whitead ,

We have now made DECIMER V2.0 available to everyone. I think you would get better results if you were to generate the SMILES for the image you have included. Also check out our new web app: https://decimer.ai

Example:

```python
from DECIMER import predict_SMILES

path = "path/to/img"
predict_SMILES(path)
```
![image](https://user-images.githubusercontent.com/30716951/169168457-8da71bdc-ee3c-4734-89a2-bca93e2120cc.png)

- Predicted SMILES: CC(CC1=CC2=C(C=C1)OCO2)NC
- Redepicted using: https://www.simolecule.com/cdkdepict/depict.html
![image](https://user-images.githubusercontent.com/30716951/169168520-a7faa7e7-12a5-416f-ae97-c10f5f4e9910.png)


-Kohulan

**Comment by Kohulan** [comment]
Hi @Adafede ,

Using the provided image above the new version of DECIMER gives the following result,

- Predicted SMILES: CC1C=C(C(=O)[C@]2([C@H]1C[C@@H]3[C@@]4([C@H]2C(=O)C(=C([C@@H]4CC(=O)O3)C)OC)C)C)OC
- Redepicted Image:
![image](https://user-images.githubusercontent.com/30716951/169168860-35852746-f6ab-4f47-8fb6-0858ea3bfd58.png)

Hope this helps now :)
-Kohulan

**Comment by Adafede** [comment]
Hi @Kohulan!

Thank you very much!

I have already been using the web interface and saw great improvements!
Looks like RanDepict did a great job 😊 

Best,

**Comment by whitead** [comment]
Great! Congrats on the new release.
