### ISSUE TITLE
add support for webp and maybe web image URLs

### ISSUE THREAD

**Issue by egonw** [Kohulan/DECIMER-Image_Transformer#24]
Allowing people to drag-n-drop images from articles, like https://www.nature.com/articles/s41586-022-04828-5/figures/1, which often are `.webp` format nowadays:

![image](https://user-images.githubusercontent.com/26721/174316395-bee01bf6-ac81-4154-ac15-743eee29978d.png)

**Comment by Kohulan** [comment]
@OBrink This should be an issue for [DECIMER-Web](https://github.com/OBrink/DECIMER_Web), I am unable to transfer the issue, Could you have a look at it?

**Comment by OBrink** [comment]
I have opened a new issue [here](https://github.com/OBrink/DECIMER_Web/issues/41) and will close this issue here. It is on my current to-do-list to implement this, it should not be rocket science to make it work :)
