### ISSUE TITLE
Add data to your pretrained model

### ISSUE THREAD

**Issue by pythonnewbie3** [Kohulan/DECIMER-Image_Transformer#27]
Is there a way to just add data to the model you already trained, without retraining it completely?

**Comment by Kohulan** [comment]
You do not have to retrain completely. You can start your training from the model weights provided.

**Comment by pythonnewbie3** [comment]
Thank you. Do you have a documentation where this is explained?

**Comment by Kohulan** [comment]
No, we don't have it but you could refer to any Tensorflow tutorials regarding fine-tuning from previous checkpoints. I will try to add information regarding fine-tuning when I get time.

**Comment by pythonnewbie3** [comment]
Thanks alot, do you have a tutorial on how to prepare the data to continue at the checkpoint?

**Comment by Kohulan** [comment]
No, we don't. But if you want to train the model on your own you have to generate [TFRecord](https://www.tensorflow.org/tutorials/load_data/tfrecord) files out of your images. Using the following python files: 
https://github.com/Kohulan/DECIMER-Image_Transformer/tree/DECIMER_V1.0/TFRecord_Utils

**Comment by pythonnewbie3** [comment]
Where can I find the modelweights?

**Comment by Kohulan** [comment]
You can find  model weights here: https://zenodo.org/record/7180845
The record contains the latest DECIMER V1.0. checkpoints and DECIMER V2.0 models. 
It is already on the readme file please check it once.

**Comment by pythonnewbie3** [comment]
I encountered problems when installing decimer on a different computer: 
'urllib.error.HTTPError: HTTP Error 403: Forbidden'
I think the fire wall is blocking this IP address.
Where do I have to unzip them on the computer?

**Comment by Kohulan** [comment]
I am not sure which OS you are trying to install DECIMER. I would highly recommend using Linux-based operating systems.
The models should be downloaded and unzipped into the user directory, for example: ```/Users/user_name/.data/DECIMER-V2```

**Comment by pythonnewbie3** [comment]
Thanks alot. :-)
