### ISSUE TITLE
Reorganize README

### ISSUE THREAD

**Issue by cthoyt** [Kohulan/DECIMER-Image_Transformer#3]
Right now, the README is very confusing for any potential users. Typically I don't think the README of a code repository should read the same way as a scientific work. It should start with at most one or two lines about what the package does, a link to the relevant paper. Then, you should have the quick version of how to install the code. Then, minimal examples that showcase what the package does. After that, anything is fair game - this is where you could elaborate on some of the scientific aspects, though I would suggest cutting this completely from the README - you have a scientific paper for fluffy words. They can also be part of the first page of more thorough documentation, which I will suggest in an alternate issue

**Comment by Kohulan** [comment]
ReadMe Modified with how to train and added links to PyPi
