### ISSUE TITLE
Model doesn't perform well

### ISSUE THREAD

**Issue by AlmaEvans2910** [Kohulan/DECIMER-Image_Transformer#47]
The model performs badly on hand drawn images or pictures taken by phone.

**Comment by AlmaEvans2910** [comment]
It wasn't able to recognize structures like these, as well. 
![22w](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/133029571/fec0373f-6f35-4d0e-bde1-e287591b213b)
![image](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/133029571/b3b2137c-6fd8-4ba9-b748-4af8aa6a96a7)

**Comment by BinaryBlaze291** [comment]
The model cannot recognize pretty simple structures. I tried all of these and it gives wrong results

![ethanol](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/5e45ed30-dcfc-4e87-a797-883a0352fca3)
![structural-formula-propane-chemical-formula-skeletal-formula-chemical-compound-png-favpng-at97Lc9JR8GCLVnKdUFphiUpg](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/61ada58d-3dfb-40e9-ae60-af4dc0cf0eaa)
![ethane-flat3134352308631709013](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/73a93671-0093-4823-843a-3d3b2966c89e)
![q_3_21_july201166500841672020](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/92e58993-4e03-4bf1-94db-dd26fcd519e3)
