### ISSUE TITLE
Can I get the trained model as a .h5 or tf model format?

### ISSUE THREAD

**Issue by weathon** [Kohulan/DECIMER-Image_Transformer#49]
### Issue Type

Support

### Source

GitHub (source)

### DECIMER Image Transformer Version

2.0.0

### Current Behaviour?

Can I get the trained model as a .h5 or tf model format that I can load? I did not find the model in the repo

### Standalone code to reproduce the issue

```shell
# Not code related question
# Can I get the trained model as a .h5 or tf model format that I can load? I did not find the model in the repo
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kohulan** [comment]
Hi @weathon ,

You can find the models here: https://zenodo.org/record/7624994, which is already listed on ReadME.md. It is in a .pb format which works with Tensorflow without any issues. Hope that helps 😃 .

- Kohulan

**Comment by weathon** [comment]
Ah I found it in read me. Thanks. It took me a while though because it is
an icon not a link so I skipped it when skimming. I suggest change it into
a link.
But anyway, thank you!

**Comment by weathon** [comment]
This is a tf model not a Keras model so I am not sure if I can take only a few layers out. I want only the decoder, is it possible t do that?

**Comment by weathon** [comment]
@Kohulan

**Comment by Kohulan** [comment]
@weathon, We don't use Keras .h5 format, maybe you could use some converters?
