### ISSUE TITLE
Host documentation on ReadTheDocs

### ISSUE THREAD

**Issue by cthoyt** [Kohulan/DECIMER-Image_Transformer#5]
After #4, you can set up ReadTheDocs.org to automatically build and host the sphinx docs

**Comment by cthoyt** [comment]
Now that #12 is done, you can navigate to the site and do this already

**Comment by cthoyt** [comment]
Ahh there are a few tricks I forgot to mention - you'll need to install some extra dependencies. this can be done with `pip install -e .[docs]` or check in the `setup.cfg` for the extra requirements heading for the list.

**Comment by Kohulan** [comment]
> Ahh there are a few tricks I forgot to mention - you'll need to install some extra dependencies. this can be done with `pip install -e .[docs]` or check in the `setup.cfg` for the extra requirements heading for the list.

But the above error is happening in ReadtheDocs website when I try to build.

**Comment by cthoyt** [comment]
See https://github.com/Kohulan/DECIMER-Image_Transformer/pull/13 - this tells RTD to install those extras
