### ISSUE TITLE
Integration with RDKIT for adding more features to it like providing structures in different formats like .sdf and .mol

### ISSUE THREAD

**Issue by shubhamkharbanda** [Kohulan/DECIMER-Image_Transformer#50]
### Issue Type

Feature Request

### Source

GitHub (source)

### DECIMER Image Transformer Version

2.2.2

### Current Behaviour?

Integration with RDKIT for adding more features to it like providing structures in different formats like .sdf and .mol

### Standalone code to reproduce the issue

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kohulan** [comment]
Hi,

I don't think this is necessary because you can easily integrate RDKit directly into your code.
