### ISSUE TITLE
 Archive repository on Zenodo

### ISSUE THREAD

**Issue by cthoyt** [Kohulan/DECIMER-Image_Transformer#6]
While GitHub is an excellent place to centralize your code and keep it under version control, it is not so appropriate for archiving the state of the repository. [Zenodo](https://zenodo.org/) is a proper alternative, and it will even make your life easy by connecting to GitHub. I'd recommend following [this tutorial](https://genr.eu/wp/cite/) to:

1. log in to Zenodo with your GitHub account
2. Enable its usage on the https://github.com/Kohulan user
3. Create a "release" on GitHub, which automatically notifies Zenodo to make an archive
4. Go to the Zenodo page and grab the newly minted DOI which corresponds to the code as a resource
   a. Put the badge on the GitHub page (it will allow you to copy+paste the markdown already prepared for you)
   b. Put the DOI in your manuscript and mention that you're using Zenodo to do it.

I personally thing Zenodo is the best tool for code because of its integration with GitHub, but other services exist for archiving your research output that are also good, such as Figshare.

**Comment by Kohulan** [comment]
Thank you for the nice suggestion. The initial release is now achieved in Zenodo and once I will update the documentation I will do another release.

**Comment by cthoyt** [comment]
Don't forget to put a fancy badge in the readme after :)

**Comment by Kohulan** [comment]
Yup, it is already there in the readme. :)
