### ISSUE TITLE
Deploy to PyPI

### ISSUE THREAD

**Issue by cthoyt** [Kohulan/DECIMER-Image_Transformer#7]
Since the package will be pip-installable after #2 and does not rely on any exotic dependencies, you should deploy it to PyPI. If you've never done this before, first, bump the version in `setup.cfg` from 0.0.1-dev to 0.0.1. Then, follow these steps in the bash in the root directory of the repository:

```bash
python3 setup.py -q sdist bdist_wheel 
python3 -m pip install twine
twine upload --skip-existing dist/*
```

You should do this step after you name a certain version as a "release" and upload to Zenodo (as outlined in #6) then immediately follow-up with a commit to bump the version in `setup.cfg` from 0.0.1 to 0.0.2-dev. Later, when you're done with version 0.0.2-dev (or whatever you want to call it), you take away the `-dev` suffix before releasing again. This suffix is important because it lets users know that they're not on stable versions if they're installing from github's master (main) branch

Also, please include in your manuscript that your code is available through PyPI! There are many potential users who won't be comfortable with cloning the repo or even using the tricky git+https:// way of installing through GitHub who would benefit from easy installation through PyPI.

**Comment by Kohulan** [comment]
The decimer package is now alive in PyPI!

**Comment by Kohulan** [comment]
Thank you! The badge added. 😃 
I guess now I have to work on the documentation and some code cleanup!
