### ISSUE TITLE
Backbone CNN Model

### ISSUE THREAD

**Issue by qbKhanh** [Kohulan/DECIMER-Image_Transformer#75]
### Issue Type

Questions

### Source

GitHub (source)

### DECIMER Image Transformer Version

Not relevant

### OS Platform and Distribution

Not relevant

### Python version

Not relevant

### Current Behaviour?

First, I want to thank for your hard-working with an awesome open-source. I just have a naive question that Why do you choose EfficientNet for backbone CNN model but not ResNet or others?

Thank for reading! Hope you reply soon.

### Standalone code to reproduce the issue

```shell
Not relevant
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qbKhanh** [comment]
@Kohulan,
Thank for your quick support. I have another question that How much data that you think is enough to fine-tune on?

**Comment by Kohulan** [comment]
@qbKhanh , 
I would recommend trial and error in this regard. As a starting point, I would recommend 1 million images.

**Comment by qbKhanh** [comment]
@Kohulan,
Thank you, but 1 million images would be a big deal!
