### ISSUE TITLE
Convert from Tensorflow into Pytorch framework

### ISSUE THREAD

**Issue by qbKhanh** [Kohulan/DECIMER-Image_Transformer#76]
### Issue Type

Questions

### Source

GitHub (source)

### DECIMER Image Transformer Version

Not relevant

### Current Behaviour?

Hello,
Have you ever thinked about converting your open-source from Tensorflow into Pytorch? 
Best,
Khanh

### Standalone code to reproduce the issue

```shell
Not relevant
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kohulan** [comment]
We have no plan to do that.
- Kohulan
