### ISSUE TITLE
How to get the positional informations of the molecule

### ISSUE THREAD

**Issue by Liaokang123456** [Kohulan/DECIMER-Image_Transformer#77]
### Issue Type

Questions

### Source

GitHub (source)

### DECIMER Image Transformer Version

2.0

### Current Behaviour?

from DECIMER import predict_SMILES

# Chemical depiction to SMILES translation
image_path = "path/to/imagefile"
SMILES = predict_SMILES(image_path)
print(SMILES)

The SMILES do not have the atom coordinates.
How to get the positional information? 
Thanks!

### Standalone code to reproduce the issue

```shell
from DECIMER import predict_SMILES

# Chemical depiction to SMILES translation
image_path = "path/to/imagefile"
SMILES = predict_SMILES(image_path)
print(SMILES)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OBrink** [comment]
Hey @Liaokang123456,

Thank you for your interest in DECIMER! We are currently training a model that is capable of generating cxSMILES with atom coordinates. It will appear here in the repository in the upcoming months after training and validation are done. The current version only generates a SMILES string without the positional information of the atoms in the image.

Kind regards,
Otto
