### ISSUE TITLE
I can't find Transformer_decoder.Transformer in Transformer_decoder.py file.

### ISSUE THREAD

**Issue by hml1996-fight** [Kohulan/DECIMER-Image_Transformer#79]
just "AttributeError: module 'Transformer_decoder' has no attribute 'Transformer'" 
Dose it mean Transformer_decoder.Decoder?

**Comment by OBrink** [comment]
Hello @hml1996-fight,

Could you specify what you have done that caused this error? If possible, provide a code example that I can use to reproduce the error please.

Kind regards,
Otto

**Comment by hml1996-fight** [comment]
I just run DECIMER/DECIMER_EfficinetNetV2_Transfomer_Trainer.py file 
![image](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/72264324/79309dd7-9a0b-43ed-a0f3-3936851dd7a6)
I mean Transformer_decoder.py file lacks a function named Transformer.

**Comment by OBrink** [comment]
Ah, apparently, this file has not been updated after changing to a Transformer-Decoder-Only model as a decoder. `Transformer_decoder.Decoder` should do the trick :)

**Comment by hml1996-fight** [comment]
OK. I solved it by set `Transformer_decoder.Decoder`, but a new problem arose.
the error is :
![image](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/72264324/e0854eab-c21c-466e-8fd4-d1d1879f5392)

i find `d_model` is set by 
![image](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/72264324/0173380c-3f60-4760-abe3-45503897b246)
IMG_EMB_DIM is a tuple

**Comment by hml1996-fight** [comment]
i sloved it by set `d_model = d_model[1]` .
Thanks a lot!!!

**Comment by OBrink** [comment]
Great, let me know if you need help with anything else 🙂

**Comment by hml1996-fight** [comment]
OK. now i can train DECIMER transformer with my own dataset.
but i want to pretrain this model with my dataset, could you give me your model.ckpt file rather than model.pd file.
Thanks a lot.
