### ISSUE TITLE
How can the decimer code be used from Python?

### ISSUE THREAD

**Issue by cthoyt** [Kohulan/DECIMER-Image_Transformer#8]
Currently, the package gives a command line tool. There should also be an example in the README on how to import the code from inside your own python script and use it (this will make more sense after #2)

**Comment by pythonnewbie3** [comment]
@cthoyt Could you share on how to use it from python?

**Comment by Kohulan** [comment]
@pythonnewbie3 

Clone the Repository to your local storage and then, inside python
```python
import src.decimer.DECIMER as decimer
model_name = “Isomeric"
img_path = “caffeine.png”
caffeine_smiles = decimer.predict_SMILES(img_path,model_name)
print(caffeine_smiles)
```
Hope this helps for now.
