### ISSUE TITLE
If I only want to get the result of EfficientNet, could you give me some suggest about how to do? 

### ISSUE THREAD

**Issue by pjc12345678** [Kohulan/DECIMER-Image_Transformer#80]
the question is on the title.  now I can run decimer.py to get the result of SMILES, but can't run the trainer and predictor---I can't find correlative doc.     
                  Thanks much.

**Comment by OBrink** [comment]
Hey @pjc12345678,

Please have a look at #65, I think your question has been answered there.

Let me know if I can help you with anything else 🙂

Otto
