### ISSUE TITLE
Name Error when installing

### ISSUE THREAD

**Issue by LaurinL0801** [Kohulan/DECIMER-Image_Transformer#83]
https://github.com/Kohulan/DECIMER-Image_Transformer/blob/818375498dc5594d30b6022109444e8704146488/DECIMER/utils.py#L82

When trying to install DECIMER to my code I encountered the following error **NameError: name 'shutil' is not defined**. This could however be easily be solved by adding `shutil` to the imports.

**Comment by Kohulan** [comment]
@LaurinL0801 ,

Did you install using pip?
