### ISSUE TITLE
Working with tokenizer

### ISSUE THREAD

**Issue by Tim4ik77** [Kohulan/DECIMER-Image_Transformer#87]
### Issue Type

Bug

### Source

GitHub (source)

### DECIMER Image Transformer Version

2

### Current Behaviour?

Hi, I tried to train this neural network on my dataset, but I don't quite understand how you used tokenizer when encoding the text. I didn't find any information about it in the training file. I use the following code to load the tokenizer: 
```
tokenizer = pickle.load(
    open(
        default_path.as_posix() + "/DECIMER_model/assets/tokenizer_SMILES.pkl",
        { "rb",
    )
)

```
But when I try to encode the text I get strange values: 
`tokenizer.texts_to_sequences(['O=C(O)C(CCCCn1cnc2c1NC=NCC2O)(Cc1ccccc1C(F)(F)F)C(=O)O', 'C1CCCCCCC1']) -> [[1], [1]]`

Can you please tell me how tokenizer should be used correctly?

### Standalone code to reproduce the issue

```shell
# Set path
default_path = pystow.join("DECIMER-V2")

# model download location
checkpoint_url = "https://zenodo.org/record/8093783/files/DECIMER_512_checkpoints.zip"
checkpoint_path = str(default_path) + "/DECIMER_checkpoints/"

if not os.path.exists(checkpoint_path):
    config.download_trained_weights(checkpoint_url, default_path)

# load assets

tokenizer = pickle.load(
    open(
        default_path.as_posix() + "/DECIMER_model/assets/tokenizer_SMILES.pkl",
        "rb",
    )
)

tokenizer.texts_to_sequences(['O=C(O)C(CCCCn1cnc2c1NC=NCC2O)(Cc1ccccc1C(F)(F)F)C(=O)O', 'C1CCCCC1'])
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kohulan** [comment]
The SMILES string must be split before giving it to the tokenizer. Maybe that is why it is not working also you should give Canonical and Kekulized SMILES. Hope this helps
```python
import pickle
import pystow
from DECIMER import utils

default_path = pystow.join("DECIMER-V2")
tokenizer = pickle.load(
    open(
        default_path.as_posix() + "/DECIMER_model/assets/tokenizer_SMILES.pkl",
        "rb",
    )
)

SMILES = "CN1C=NC2=C1C(=O)N(C(=O)N2C)C" #Canonical and Kekulized SMILES
split_SMILES = utils.split_and_modify_atoms(SMILES)
#C N 1 C = N C 2 = C 1 C ( = O ) N ( C ( = O ) N 2 C ) C
tokenizer.fit_on_texts([split_SMILES])
tokenizer.texts_to_sequences([split_SMILES])
#This will print: [[2, 7, 8, 2, 3, 7, 2, 9, 3, 2, 8, 2, 4, 3, 6, 5, 7, 4, 2, 4, 3, 6, 5, 7, 9, 2, 5, 2]]
```
